### ISSUE TITLE
Hugging Face token not found

### ISSUE THREAD

**Issue by elschilling** [nousr/koi#1]
I am trying to run locally but when run python server.py I get this message: 

`OSError: You specified use_auth_token=True, but a Hugging Face token was not found.`

I am searching ways to set the auth token, any help would be appreciated.

**Comment by nerdyrodent** [comment]
That's the diffusers model so you'll need a huggingface account at to use ```huggingface-cli login```

**Comment by tocram1** [comment]
...and after that, don't forget to accept the model's terms of service form here : https://huggingface.co/CompVis/stable-diffusion-v1-4

**Comment by nousr** [comment]
908a5ee889b40607537cc87e6f045b726edde097 thanks everyone! i added a note in the readme about this @elschilling let me know if you run into any more errors!

**Comment by elschilling** [comment]
Thanks! I did login and managed to get the server running locally in an anaconda env, buy when I click on the Dream button I get this error:
` RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 9.78 GiB total capacity; 7.52 GiB already allocated; 193.19 MiB free; 7.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by nousr** [comment]
it sounds like you are running out of memory @elschilling. running stable diffusion with an image editing software / other apps open may use more resources than stable diffusion alone.

I recommend trying the google colab backend if you are unsable to get it running locally.
