### ISSUE TITLE
Returned image is heavily JPEG-ed

### ISSUE THREAD

**Issue by jameshfisher** [nousr/koi#11]
The server is sending back poor-quality JPEGs - IMO it should default to high quality, possibly lossless

**Comment by jameshfisher** [comment]
I changed it to

```
    return_image.save(return_bytes, format="PNG")
    return_bytes.read()
    return_bytes.seek(0)

    return send_file(return_bytes, mimetype="image/png")
```

Krita seems to handle this fine

**Comment by nousr** [comment]
thank you for testing this--would you like to make a PR to update this for everyone?

**Comment by nousr** [comment]
i went ahead and fixed this issue as I saw you closed your PR! thanks for testing stuff out though :D
