### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by lynchman100** [nousr/koi#19]
Hey, first off this is contribution.
I tried running from colab and i go this error as soon as I hit dream for the first time.

AttributeError
Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
Sat Sep  3 13:17:42 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\jason\AppData\Roaming\krita\pykrita\koi\koi.py in pingServer(self=<koi.koi.Koi object>)
  133         # get a pointer to the image's bits and add them to the new layer
  134         ptr = returned_image.bits()
  135         ptr.setsize(returned_image.byteCount())
  136         dream_layer.setPixelData(
  137             QByteArray(ptr.asstring()),
ptr = None
ptr.setsize undefined
returned_image = <PyQt5.QtGui.QImage object>
returned_image.byteCount = <built-in method byteCount of QImage object>
AttributeError: 'NoneType' object has no attribute 'setsize'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'setsize'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\jason\AppData\Roaming\krita\pykrita\koi\koi.py", line 135, in pingServer
    ptr.setsize(returned_image.byteCount())
AttributeError: 'NoneType' object has no attribute 'setsize'

I don't have a clue about most of this stuff, i just followed as best i could.
I would really appreciate so direction.
The file size is 512 by 512 and there is one layer as suggested.

**Comment by nousr** [comment]
This typically happens when you forget to add "/api/img2img" to the end of your endpoint when copying over the ngrok token.

More useful error messages will be coming in the next week, so I appreciate the patience as we move forward!

**Comment by lynchman100** [comment]
hey man i tried this several times as well as reinstalling it still gives the error.
