### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'setsize'

### ISSUE THREAD

**Issue by KyonaLuya** [nousr/koi#29]
Trying to get this up and running with Colab. I'm getting this error:

AttributeError
Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
Mon Sep  5 10:32:53 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Program Files\Krita (x64)\share\krita\pykrita\koi\koi.py in pingServer(self=<koi.koi.Koi object>)
  133         # get a pointer to the image's bits and add them to the new layer
  134         ptr = returned_image.bits()
  135         ptr.setsize(returned_image.byteCount())
  136         dream_layer.setPixelData(
  137             QByteArray(ptr.asstring()),
ptr = None
ptr.setsize undefined
returned_image = <PyQt5.QtGui.QImage object>
returned_image.byteCount = <built-in method byteCount of QImage object>
AttributeError: 'NoneType' object has no attribute 'setsize'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'setsize'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Program Files\Krita (x64)\share\krita\pykrita\koi\koi.py", line 135, in pingServer
    ptr.setsize(returned_image.byteCount())
AttributeError: 'NoneType' object has no attribute 'setsize'

Colab is spitting out "INFO:werkzeug:127.0.0.1 - - [05/Sep/2022 14:34:43] "POST / HTTP/1.1" 404 -"

I am getting a new blank layer in Krita every time I try to run.

I can't figure out what I am doing wrong or if this is a bug or what.

**Comment by nousr** [comment]
i think you may have copied the wrong ip address from NGROK? when using colab you won't use the 127.0.0.1 address

can you double check which one you are using?

**Comment by KyonaLuya** [comment]
> 

I forgot to append the API endpoint. It is working now. Thanks!
