### ISSUE TITLE
No external IP

### ISSUE THREAD

**Issue by mikel2000** [nousr/koi#32]
I don't get any longer an external IP, before it did work. Instead this error message is shown. I already restarted and also dropped the runtime, but it didn't help.

```
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.

Finished!
 * Serving Flask app '__main__'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000/
INFO:werkzeug:Press CTRL+C to quit
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1177, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_ngrok.py", line 70, in start_ngrok
    ngrok_address = _run_ngrok()
  File "/usr/local/lib/python3.7/dist-packages/flask_ngrok.py", line 38, in _run_ngrok
    tunnel_url = j['tunnels'][0]['public_url']  # Do the parsing of the get
IndexError: list index out of range
```
Thanks!

**Comment by mikel2000** [comment]
Possibly I hit a limit of the free ngrok plan (requesting too often an external IP). Hopefully it will work again, when I try it tomorrow. Other ideas are of course still welcome :).

**Comment by nousr** [comment]
usually when this happens I'm able to stop the sever-cell and restart it...i think sometimes you just get unlucky? your idea may be the case as well, however.

**Comment by mikel2000** [comment]
Thanks. I'll try it tomorrow again and hope the best :).

**Comment by mikel2000** [comment]
Like assumed, it was only a temporary issue. It works now again.
