### ISSUE TITLE
NSFW no allow a cat and a white image

### ISSUE THREAD

**Issue by Postconceptlab** [nousr/koi#46]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.

can i fix it ?

**Comment by Postconceptlab** [comment]
i think i have missed something help needed 

python3 server.py
Loading Model...
{'trained_betas'} was not found in config. Values will be initialized to default values.
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
Finished!
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8888
 * Running on http://192.168.0.16:8888
Press CTRL+C to quit
Accept-Encoding: identity
Transfer-Encoding: chunked
Host: 127.0.0.1:8888
User-Agent: Python-urllib/3.10
Variations: 1
Prompt: A beautiful mountain landscape in the style of greg rutkowski, oils on canvas.
Steps: 32
Seed: 1337
Sketch-Strength: 0.25
Prompt-Strength: 7.5
Content-Type: application/octet-stream
Connection: close


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  5.87it/s]
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
127.0.0.1 - - [12/Sep/2022 12:23:56] "POST /api/img2img HTTP/1.1" 200 -

**Comment by nousr** [comment]
you aren't missing anything--unfortunately the default Safety checker is just really strict :/

when i get back to working on the new backend this will be removed
