### ISSUE TITLE
[Tutorial Request] Could you give notes on how to use Google Collab to provide an endpoint?

### ISSUE THREAD

**Issue by winterstein** [nousr/koi#47]
Thank you for your work. Sadly I don't have a graphics card. Could you give notes or a link on how to use Google Collab to provide an endpoint?

Thank you!

**Comment by nousr** [comment]
have you looked at the google colab notebook provided? I feel that it is fairly well explained--but if you have suggestions for improving it I'd appreciate feedback as always 😄
