### ISSUE TITLE
Setup the backend server gives Errors

### ISSUE THREAD

**Issue by Serasul1984** [nousr/koi#50]
I made an screenshot of it
[https://drive.google.com/file/d/13V4rhtpQY1OVnWBfKK5eEu_qivpixVbw/view?usp=sharing](url)

**Comment by favouraka** [comment]
1. Important! Accept the OpenRAIL license for stable diffusion here https://huggingface.co/CompVis/stable-diffusion-v1-4
2. Go to https://huggingface.co/settings/tokens and generate a new token to use.

Hope this helps!
