### ISSUE TITLE
"Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed."

### ISSUE THREAD

**Issue by jameshfisher** [nousr/koi#8]
I got it running, but the default prompt fails with this error

**Comment by nousr** [comment]
thanks for reporting this, i think the initial sketch has influence on wether or not you get this error.

the safety checker that is shipped with stable diffusion is pretty strong so sometimes you just have to be patient and tweak the settings/sketch a little.

i need to talk to some people to see wether it is a good idea to add an option to bypass the safety filter.

for now i think the answer is just 

"hang tight and keep trying different seeds"

**Comment by licjavierbarrios** [comment]
Draw cats, rats, etc. Animals for homework and everything is detected with nsfw content. The images are the same as the youtube tutorials, in those tutorials it works fine. I got tired of changing the seeds, still the same, a black image. They would have to fix the issue. 
Thank you very much for your help.

**Comment by TheKrane** [comment]
Same problem. No matter what I draw or use as a prompt, it always triggers the NSFW filter and returns a black image.

**Comment by nousr** [comment]
this is just Stability's safety filter being....strict... there's not much I can do unfortunately other than turning it off.

I agree it's frustrating; the new update coming within a week will have an option to bypass the safety filter.

**Comment by petekay** [comment]
i get the same error, even drawing an avocado or a sailing ship. it's of course not your fault, your option would be great.
