### ISSUE TITLE
"Port 5000 is in use by another program"

### ISSUE THREAD

**Issue by jameshfisher** [nousr/koi#9]
In Colab, stopping the Flask cell then running it again results in an error "Port 5000 is in use by another program". Apparently, stopping the cell does not stop free up the port

**Comment by jameshfisher** [comment]
Poor workaround: restart runtime then re-run the Flask cell

**Comment by nousr** [comment]
yeah, i've seen this happen a few times. usually re-running the cell works for me, but i could've gotten lucky. 

i'm not sure we have any control over this--so i will close this issue for now. but if anyone has a solution feel free to re-open/PR and describe a fix!
